### ISSUE TITLE
Error: `purs` executable not found.

### ISSUE THREAD

**Issue by rubenmoor** [natefaubion/purescript-psa#27]
Both with a global and a local installation, trying to use `psa` results in this error:

```
$ psa
$HOME/.nvm/versions/node/v6.5.0/lib/node_modules/purescript-psa/output/Control.Monad.Eff.Exception/foreign.js:25
    throw e;
    ^

Error: `purs` executable not found.
    at Object.exports.error (/home/ruben/.nvm/versions/node/v6.5.0/lib/node_modules/purescript-psa/output/Control.Monad.Eff.Exception/foreign.js:8:10)
    at Object.$$throw [as throw] (/home/ruben/.nvm/versions/node/v6.5.0/lib/node_modules/purescript-psa/output/Control.Monad.Eff.Exception/index.js:58:45)
    at /home/ruben/.nvm/versions/node/v6.5.0/lib/node_modules/purescript-psa/output/Main/index.js:480:72
    at ChildProcess.<anonymous> (/home/ruben/.nvm/versions/node/v6.5.0/lib/node_modules/purescript-psa/output/Node.ChildProcess/foreign.js:106:9)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

What is `purs`? I'm using version 0.5.1.

**Comment by garyb** [comment]
`purs` is the executable for PureScript 0.11. If you're on 0.10.x for now, you'll need to downgrade `purescript-psa` to 0.4.0.

**Comment by rubenmoor** [comment]
Great, thanks.
