### ISSUE TITLE
Searching for annoucments breaks webpack purs-loader plugin

### ISSUE THREAD

**Issue by coot** [natefaubion/purescript-psa#28]
Webpack fails with this error:
```
Error: ENOENT: no such file or directory, scandir 'announcements'
    at Object.fs.readdirSync (fs.js:914:18)
    at Object.<anonymous> (/home/marcin/repos/gravicus/ospreyui/node_modules/psa/index.js:33:26)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
```

**Comment by LiamGoodacre** [comment]
Looks like you've installed `psa` (https://github.com/jpnelson/psa) not `purescript-psa`.

(I just made the same mistake)

**Comment by coot** [comment]
Thanks @LiamGoodacre
