### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Thimoteus** [natefaubion/purescript-psa#39]
I'm getting this error when compiling a (proprietary) project, though sometimes building a second time works.

**Comment by natefaubion** [comment]
I've never seen it. Any stack info?

**Comment by Thimoteus** [comment]
```
/home/evante/.nvm/versions/node/v11.1.0/lib/node_modules/purescript-psa/output/Effect/foreign.js:12
      return f(a())();
               ^

RangeError: Maximum call stack size exceeded
    at /home/evante/.nvm/versions/node/v11.1.0/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:16
    at /home/evante/.nvm/versions/node/v11.1.0/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:20
    at /home/evante/.nvm/versions/node/v11.1.0/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:16
    at /home/evante/.nvm/versions/node/v11.1.0/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:20
    at /home/evante/.nvm/versions/node/v11.1.0/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:16
    at /home/evante/.nvm/versions/node/v11.1.0/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:16
    at /home/evante/.nvm/versions/node/v11.1.0/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:20
    at /home/evante/.nvm/versions/node/v11.1.0/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:16
    at /home/evante/.nvm/versions/node/v11.1.0/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:16
    at /home/evante/.nvm/versions/node/v11.1.0/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:20
```

**Comment by natefaubion** [comment]
I wonder if this is caused by source globs being expanded by the shell? The arg parser uses `Array.foldM`, which is stack unsafe, but this would only be in the presence of a very large argument list.

**Comment by Unisay** [comment]
Same happens to me when I try to compile module with 5000 foreign exports/imports:
```
/home/yura/.npm-global/lib/node_modules/purescript-psa/output/Effect/foreign.js:11
    return function () {
                    ^

RangeError: Maximum call stack size exceeded
    at /home/yura/.npm-global/lib/node_modules/purescript-psa/output/Effect/foreign.js:11:21
    at /home/yura/.npm-global/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:16
    at /home/yura/.npm-global/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:20
    at /home/yura/.npm-global/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:16
    at /home/yura/.npm-global/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:16
    at /home/yura/.npm-global/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:20
    at /home/yura/.npm-global/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:16
    at /home/yura/.npm-global/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:16
    at /home/yura/.npm-global/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:20
    at /home/yura/.npm-global/lib/node_modules/purescript-psa/output/Effect/foreign.js:12:16
```
[Example.zip](https://github.com/natefaubion/purescript-psa/files/5179396/Example.zip)
